name: termo2-frontend
services:
- name: termo2-frontend
  source_dir: /
  github:
    repo: hpeixotosp/termo2
    branch: main
  build_command: npm run build:do
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NEXT_PUBLIC_API_URL
    value: http://143.110.196.243:3000
  - key: NODE_ENV
    value: production
  # Configuração para arquivos estáticos
  static_sites:
  - name: termo2-static
    source_dir: /
    build_command: npm run build:do
    output_dir: out
